version: '3.8'

services:
  app:
    build: .
    container_name: node-container
    ports:
      - "3000:3000"
    depends_on:
      db:
       condition: service_healthy 
    env_file:
      - .env      

  db:
    image: postgres:15
    container_name: db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:  # 👈 waits for postgres to be ready before launching the app
      test: ["CMD-SHELL", "pg_isready -U admin -d miapp"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  db-data:
