name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: AWS_ACCOUNT

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build-and-push: 
    runs-on: ubuntu-latest
    environment: AWS_ACCOUNT
    needs: test
    
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug AWS region
        run: echo "AWS Region ${{ secrets.AWS_REGION }}" 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build Docker image
        run: |
          TAG=$(date +%Y%m%d-%H%M)
          docker build --platform linux/amd64 -t node-app .
          docker tag node-app:latest ${{ secrets.ECR_REPO }}:$TAG
          docker tag node-app:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push Docker image to ECR
        run: |
          TAG=$(date +%Y%m%d-%H%M)
          docker push ${{ secrets.ECR_REPO }}:$TAG
          docker push ${{ secrets.ECR_REPO }}:latest